translate tags name in devtools panel
Tanaguru/webextension pull request #17
Opened 2021-07-22 13:02 UTC by severineFF-tanaguru

2021-07-22 13:41 UTC, rcharre requested changes

2021-07-22 13:41 UTC, rcharre commented on src/ressources/scripts/tests/content.js
> +        return a.id.localeCompare(b.id);
Attention ici comme les tags ne sont plus triés via leur traduction mais via leur id on peut se retrouver dans des cas où l'ordre ne serait plus bon à l'affichage. Pour palier à ce problème il faut trier le tableau de tags à l'affichage et non plus à l'initialisation

2021-07-22 14:14 UTC, severineFF-tanaguru commented on src/ressources/scripts/tests/content.js
> +        return a.id.localeCompare(b.id);
ok, j'ai effectué le tri à l'affichage.
Cependant, je remarque que les tags en erreur apparaissent en 1er dans l'ordre alphabétique.
Et les suivants (sans erreurs) apparaissent dans l'ordre inverse...
Je ne suis pas sûre que ce soit bien ce qui est attendu.

2021-07-22 14:35 UTC, rcharre commented on src/devtools/panel/tanaguru-devtools-panel.js
> +
Je ne sais pas si tu connais ou si tu as un interet pour ce genre de fonction mais il existe les fonction de gestion de tableau (map, reduce, ...) qui te permettent de faciliter le code sur ce genre de traitement.  Par exemple ici tu pourrais écrire :
`
response.tags.map(tag => chrome.i18n.getMessage('tag' + tag.id.charAt(0).toUpperCase() + tag.id.slice(1))
.sort((a,b) => a.name.localeCompare(b.name)
`
Ici map te sert a renvoyer une valeur calculé à partir d'une entrée de ton tableau : pour chaque tag je cherche la traduction

2021-07-22 14:37 UTC, rcharre requested changes

2021-07-22 14:37 UTC, rcharre commented on src/ressources/scripts/tests/content.js
> +    // });
Supprime si ca ne sert à rien :)

2021-07-22 15:33 UTC, severineFF-tanaguru commented on src/devtools/panel/tanaguru-devtools-panel.js
> +
je ne connaissais pas non, merci c'est top !

2021-07-22 15:42 UTC, rcharre requested changes

2021-07-22 15:42 UTC, rcharre commented on src/devtools/panel/tanaguru-devtools-panel.js
> +		response.tags.sort((a, b) => a.name.localeCompare(b.name));
la fonction map te retourne un nouveau tableau avec les nouveaux élements du coup tu dois créer une nouvelle variables pour le stocker. De plus tu effectues le sort() sur ce meme tableau tu n'as donc pas besoin de le faire en plusieurs étapes.
```
response.tags = response.tags.map(...)
    .sort(...)
```

2021-07-22 17:03 UTC, severineFF-tanaguru commented on src/devtools/panel/tanaguru-devtools-panel.js
> +		response.tags.sort((a, b) => a.name.localeCompare(b.name));
c'est bien ce que j'ai tenté au départ mais ça ne passe pas, peut-être parce que "tag" est un objet json ?
cependant de la façon dont c'est écrit là, ça semble fonctionner...

2021-07-23 08:14 UTC, rcharre commented on src/devtools/panel/tanaguru-devtools-panel.js
> +
Au temps pour moi je pensais qu'on n'avait besoin d'uniquement le nom du tag pour l'affichage alors qu'on a aussi besoin de l'id

2021-07-23 08:40 UTC, merged